#!/usr/bin/env bash
# ============================================================
#  test-run-data.sh — tests for run-data.sh logic
#
#  Tests credential parsing, remote detection, concurrency
#  adjustment, and synthetics guard behavior.
#  Does NOT actually run data ingestion — only tests the parsing.
# ============================================================

_SELF_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || echo "${BASH_SOURCE[0]}")")" && pwd)"
source "$_SELF_DIR/test-helpers.sh"


# ── Helper: simulate run-data.sh config parsing ──────────
# Extracts the same variables that run-data.sh would set
parse_run_data_config() {
  local yml="$1"

  KIBANA_PORT=$(grep -E "^ *port:" "$yml" 2>/dev/null | head -1 | awk '{print $2}')
  ES_HOST=$(grep -E "^ *(- \"?|hosts: *)https?://" "$yml" 2>/dev/null | head -1 | sed 's|^ *- *||; s|^ *hosts: *||' | tr -d '"' | tr -d ' ')
  ES_PASSWORD=$(grep -E "^ *(elasticsearch\.)?password:" "$yml" 2>/dev/null \
    | grep -v "^#" | grep -v "kibana.password" \
    | head -1 | sed 's|.*password: *||' | tr -d '"' | tr -d ' ')

  ES_PASSWORD="${ES_PASSWORD:-changeme}"

  IS_REMOTE=false
  if [[ "$ES_HOST" != *"localhost"* && "$ES_HOST" != *"127.0.0.1"* ]]; then
    IS_REMOTE=true
  fi

  DATA_USERNAME="elastic"
  DATA_PASSWORD="${ES_PASSWORD}"
}


# ══════════════════════════════════════════════════════════
#  LOCAL ES CONFIG PARSING
# ══════════════════════════════════════════════════════════

describe "run-data config parsing — local ES"

LOCAL_YML="$TEST_DIR/local-run-data.yml"
cat > "$LOCAL_YML" <<'EOF'
server:
  port: 5601
  restrictInternalApis: false

elasticsearch.hosts:
  - "http://localhost:9200"
elasticsearch.username: "kibana"
elasticsearch.password: "changeme"
EOF

it "reads Kibana port from local config"
  parse_run_data_config "$LOCAL_YML"
  assert_eq "5601" "$KIBANA_PORT"

it "reads ES host from local config"
  parse_run_data_config "$LOCAL_YML"
  assert_eq "http://localhost:9200" "$ES_HOST"

it "reads password from local config"
  parse_run_data_config "$LOCAL_YML"
  assert_eq "changeme" "$ES_PASSWORD"

it "detects local ES correctly"
  parse_run_data_config "$LOCAL_YML"
  assert_eq "false" "$IS_REMOTE"

it "always uses elastic as data username"
  parse_run_data_config "$LOCAL_YML"
  assert_eq "elastic" "$DATA_USERNAME"


# ══════════════════════════════════════════════════════════
#  REMOTE ES CONFIG PARSING
# ══════════════════════════════════════════════════════════

describe "run-data config parsing — remote ES"

REMOTE_YML="$TEST_DIR/remote-run-data.yml"
cat > "$REMOTE_YML" <<'EOF'
server:
  port: 5601
  restrictInternalApis: false

# Remote ES — generated by dev-start.sh --remote
elasticsearch:
  hosts: https://edge-oblt.es.us-west2.gcp.elastic-cloud.com:443
  username: kibana_system_user
  password: remote-pw-789
  ssl:
    verificationMode: none
EOF

it "reads Kibana port from remote config"
  parse_run_data_config "$REMOTE_YML"
  assert_eq "5601" "$KIBANA_PORT"

it "reads remote ES host"
  parse_run_data_config "$REMOTE_YML"
  assert_eq "https://edge-oblt.es.us-west2.gcp.elastic-cloud.com:443" "$ES_HOST"

it "reads password from remote config"
  parse_run_data_config "$REMOTE_YML"
  assert_eq "remote-pw-789" "$ES_PASSWORD"

it "detects remote ES correctly"
  parse_run_data_config "$REMOTE_YML"
  assert_eq "true" "$IS_REMOTE"

it "still uses elastic as data username for remote"
  parse_run_data_config "$REMOTE_YML"
  assert_eq "elastic" "$DATA_USERNAME"

it "uses ES password as data password"
  parse_run_data_config "$REMOTE_YML"
  assert_eq "remote-pw-789" "$DATA_PASSWORD"


# ══════════════════════════════════════════════════════════
#  CONCURRENCY ADJUSTMENT
# ══════════════════════════════════════════════════════════

describe "concurrency settings"

it "uses default concurrency for local ES"
  parse_run_data_config "$LOCAL_YML"
  epc=50; payload=10000; conc=5
  if [[ "$IS_REMOTE" == true ]]; then
    epc=10; payload=1000; conc=1
  fi
  assert_eq "50" "$epc" "events-per-cycle should be 50 for local"

it "reduces concurrency for remote ES"
  parse_run_data_config "$REMOTE_YML"
  epc=50; payload=10000; conc=5
  if [[ "$IS_REMOTE" == true ]]; then
    epc=10; payload=1000; conc=1
  fi
  assert_eq "10" "$epc" "events-per-cycle should be 10 for remote"

it "reduces payload for remote ES"
  parse_run_data_config "$REMOTE_YML"
  epc=50; payload=10000; conc=5
  if [[ "$IS_REMOTE" == true ]]; then
    epc=10; payload=1000; conc=1
  fi
  assert_eq "1000" "$payload" "payload should be 1000 for remote"

it "reduces concurrency count for remote ES"
  parse_run_data_config "$REMOTE_YML"
  epc=50; payload=10000; conc=5
  if [[ "$IS_REMOTE" == true ]]; then
    epc=10; payload=1000; conc=1
  fi
  assert_eq "1" "$conc" "concurrency should be 1 for remote"


# ══════════════════════════════════════════════════════════
#  PASSWORD DEFAULTS
# ══════════════════════════════════════════════════════════

describe "password defaults"

NO_PW_YML="$TEST_DIR/no-password.yml"
cat > "$NO_PW_YML" <<'EOF'
server:
  port: 5601

elasticsearch.hosts:
  - "http://localhost:9200"
elasticsearch.username: "kibana"
EOF

it "defaults to 'changeme' when no password in config"
  parse_run_data_config "$NO_PW_YML"
  assert_eq "changeme" "$ES_PASSWORD"


# ══════════════════════════════════════════════════════════
#  SYNTHETICS GUARD
# ══════════════════════════════════════════════════════════

describe "synthetics remote guard"

it "blocks synthetics on remote ES"
  parse_run_data_config "$REMOTE_YML"
  if [[ "$IS_REMOTE" == true ]]; then
    result="blocked"
  else
    result="allowed"
  fi
  assert_eq "blocked" "$result"

it "allows synthetics on local ES"
  parse_run_data_config "$LOCAL_YML"
  if [[ "$IS_REMOTE" == true ]]; then
    result="blocked"
  else
    result="allowed"
  fi
  assert_eq "allowed" "$result"


# ── Print results ─────────────────────────────────────────
print_summary
